### ISSUE TITLE
Best communication channel to work together

### ISSUE THREAD

**Issue by alcantara09** [Brazilian-Institute-of-Robotics/simulation-gpu_sonar_simulation#19]
We are currently developing solutions on top of this package and we want know what would be the best channel of communication to ease any pull request, code review and new functionalities, in order to avoid major changes to be added at once?

**Comment by romulogcerqueira** [comment]
Hi @alcantara09 , this is the right channel to work together. Unfortunately I'm very busy with other stuffs, however I will have a look on your PR soon.
